[tool.poetry]
name = "electricitymap-contrib-config"
version = "0.1.0"
description = ""
authors = ["electricityMap team <hello@electricityMap.org>"]
packages = [
    { include = "electricitymap" }
]
include = ["./*.json"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pylint = "^2.6.0"

[tool.poetry.scripts]
lint = 'scripts:lint'
test = 'scripts:test'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
