# A workflow to validate JSON files against JSON Schemata

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on pull request events but only for JSON files
  pull_request:
    branches: [ '**' ]
    paths: [ '**.json' ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  validate_json_schema:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Installs Python
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      # Installs https://github.com/Julian/jsonschema
      - name: Install jsonschema
        timeout-minutes: 1
        run: python3 -m pip install jsonschema
      - name: Validate zones.json
        timeout-minutes: 1
        run: python3 -m jsonschema config/zones.schema.json -i config/zones.json
      - name: Validate exchanges.json
        timeout-minutes: 1
        run: python3 -m jsonschema config/exchanges.schema.json -i config/exchanges.json
